### ISSUE TITLE
enhancement - scenekit / arkit helpers to display planet locations based off user location / JD 

### ISSUE THREAD

**Issue by johndpope** [DJBen/SpaceTime#11]
I'm looking to display planets based off user location.

Perhaps we can cherry pick some of the code / logic from @calda .
https://github.com/HTN-2017/AR-Planes

https://www.youtube.com/watch?v=dnYHQ-7wlag
screen shot 2018-03-09 at 11 18 31 am

I'm looking for something as trivial as
here's my date / time / coordinate - where is the corresponding planet pluto / mars / etc.
https://github.com/HTN-2017/AR-Planes/blob/master/AR%20Planes/Model/Flight.swift

struct Flight {
    
    // MARK: - Properties
    
    let icao: String
    let callsign: String
    let longitude: Double
    let latitude: Double
    let altitude: Double
    let noseHeading: Double
    let groundVelocity: Double
    let verticalVelocity: Double
    
    var location: CLLocation {
        let coordinate = CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
        
        //note: CLLocation also accepts heading and speed, could be useful?
        return CLLocation(
            coordinate: coordinate,
            altitude: altitude,
            horizontalAccuracy: 1,
            verticalAccuracy: 1,
            timestamp: Date())
    }

func sceneKitCoordinate(relativeTo userLocation: CLLocation) -> SCNVector3 {
        let distance = location.distance(from: userLocation)
        let heading = userLocation.coordinate.getHeading(toPoint: location.coordinate)
        let headingRadians = heading * (.pi/180)
        
        let distanceScale: Double = 1/140
        let eastWestOffset = distance * sin(headingRadians) * distanceScale
        let northSouthOffset = distance * cos(headingRadians)  * distanceScale
        
        let altitudeScale: Double = 1/140 //1/20
        let upDownOffset = altitude * altitudeScale
        
        //in .gravityAndHeading, (1, 1, 1) is (east, up, south)
        return SCNVector3(eastWestOffset, upDownOffset, -northSouthOffset)
    }

**Comment by DJBen** [comment]
Hi, I shared my stellerium project [Graviton](https://github.com/DJBen/Graviton) with you. I believe I did something similar so maybe you can get inspiration from it. Feel free to grab any code blocks and tailor to your needs. I can take a deeper look this weekend.

**Comment by johndpope** [comment]
Thanks again @DJBen  - going to close this / among my other older github issues that I still have open.
